# Generated by Django 5.0.6 on 2024-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
