# Generated by Django 5.0.6 on 2024-06-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
